version: '3'
services:
  webapp:
    image: ktor-koin:latest
    environment:
      - MONGO_HOST = mongodb
      - ME_CONFIG_MONGODB_ADMINUSERNAME = root
      - ME_CONFIG_MONGODB_ADMINPASSWORD = example
    ports:
      - 8080:8080
    links:
      - mongodb
    depends_on:
      - mongodb
  mongodb:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME = root
      - MONGO_INITDB_ROOT_PASSWORD = example
    ports:
      - 27017:27017
